In [1]:
import torch

In [4]:
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [5]:
print(x.numel())

12


In [8]:
print(x.shape)

torch.Size([12])


In [9]:
x = x.reshape(2, 6)
print(x)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 5, 6))

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [12]:
torch.randn((3, 2, 5))

tensor([[[-0.3662,  0.0966, -1.1578,  0.0538, -1.7976],
         [ 1.7538,  1.4363,  0.3660, -0.3054, -0.6634]],

        [[ 0.1240, -0.5935, -0.9795,  0.1310, -0.9314],
         [ 1.0707,  0.8556,  0.9956,  0.3734, -0.8341]],

        [[-1.4765, -0.7530, -1.0772,  1.3660, -0.4306],
         [ 0.2264,  1.0606,  1.4593,  0.8361, -0.9294]]])

In [13]:
torch.tensor([[2, 1, 4], [3, 7, 5], [8, 9, 6]])

tensor([[2, 1, 4],
        [3, 7, 5],
        [8, 9, 6]])

In [14]:
x[-1]

tensor([ 6.,  7.,  8.,  9., 10., 11.])